Linux build

diff --git a/tracker/makefile b/tracker/makefile
--- a/tracker/makefile
+++ b/tracker/makefile
@@ -42,6 +42,21 @@ macOS macOS-deploy:
 windows-deploy:
 	$(MAKE) -f Makefile.windows windows-deploy
 
+.PHONY: linux-package linux-package-deploy
+linux-package:
+	./build-linux-docker.sh
+
+linux-package-deploy: linux-package
+	mkdir -p ../../releases
+	$(eval VERSION := $(shell grep 'appVersion.*=' src/version.c | cut -d'"' -f2))
+	@if [ -f build/linux/ChipNomad-$(VERSION)-Linux-x86_64.tar.gz ]; then \
+		mv build/linux/ChipNomad-$(VERSION)-Linux-x86_64.tar.gz ../../releases/ChipNomad-$$(date +%Y-%m-%d)-$(VERSION)-Linux-x86_64.tar.gz; \
+		echo "Linux package created: ../../releases/ChipNomad-$$(date +%Y-%m-%d)-$(VERSION)-Linux-x86_64.tar.gz"; \
+	else \
+		echo "Error: Package not found at build/linux/ChipNomad-$(VERSION)-Linux-x86_64.tar.gz"; \
+		exit 1; \
+	fi
+
 .PHONY: deploy-all
 deploy-all:
 	./deploy-all.sh
@@ -65,3 +80,6 @@ clean-portmaster:
 
 clean-macOS:
 	rm -rf build/macos
+
+clean-linux:
+	rm -rf build/linux
